### PR TITLE
feat(converters): add typecastexpression

### PR DESCRIPTION
**Pull request by gergelyke**
not sure if I've missed anything - please let me know if I did, and I'll update accordingly!

### CODE REVIEW

**Comment by Noviny** [comment]
@gergelyke Thanks for the PR! It would be good if you can to add at least one test. We're using the tests mostly so we have a store of what the code to generate the type looks like, as well as what the output will look like for parsing.

There's a couple of other projects (kind2string and pretty-proptypes) which will need to be updated once this is merged, but that can be done after.

**Comment by gergelyke** [comment]
@Noviny sure, that makes sense - I'll add test coverage for it. Do you think the converter as is makes sense? I was not sure what should I return there

**Comment by gergelyke** [comment]
@Noviny updated, and it seems to work for our use case

**Comment by Noviny** [comment]
@gergelyke Just published a new version of extract-react-types that resolve typecastexpressions as above.

**Comment by Noviny** [comment]
Thanks for submitting this PR and driving the dev of this.

**Comment by gergelyke** [comment]
this is great, thank you very much Ben!

**Pull request closed without merging**
